package com.example.foodify.util

const val sharedPrefFileName = "foodify_shared_pref"
val countryCodeMap = mapOf(
    "American" to "us",
    "British" to "gb",
    "Canadian" to "ca",
    "Chinese" to "cn",
    "Croatian" to "hr",
    "Dutch" to "nl",
    "Egyptian" to "eg",
    "Filipino" to "ph",
    "French" to "fr",
    "Greek" to "gr",
    "Indian" to "in",
    "Irish" to "ie",
    "Italian" to "it",
    "Jamaican" to "jm",
    "Japanese" to "jp",
    "Kenyan" to "ke",
    "Malaysian" to "my",
    "Mexican" to "mx",
    "Moroccan" to "ma",
    "Polish" to "pl",
    "Portuguese" to "pt",
    "Russian" to "ru",
    "Spanish" to "es",
    "Thai" to "th",
    "Tunisian" to "tn",
    "Turkish" to "tr",
    "Ukrainian" to "ua",
    "Vietnamese" to "vn",
)